##Further filtration of cafe.input.filter.tsv generated by 
##/tools/CAFE5/python_scripts/cafetutorial_clade_and_size_filter.py
##To remove families with largest size differentials

#Usage
#filter_largest_size_differentials.R -i cafe.input.filter.tsv -o dif -a 100

#!/usr/bin/env Rscript
suppressPackageStartupMessages(library(optparse))

##Create parameters
option_list <- list(
  make_option(c("-i","--input"), type="character", default=NULL,
              help="cafe.input.filter.tsv' [default %default]",
              dest="input_filename"),
  make_option(c("-o","--output"), type="character", default="dif",
              help="output filename prefix [default %default]",
              dest="output_filename"),
  make_option(c("-a", "--min-difference"), type="numeric", default=100,
              help="minimum difference to remove [default %default]",
              dest="mina")
)
options(error=traceback)

parser <- OptionParser(usage = "%prog -i orthologs.txt -o out [options]",option_list=option_list)
opt = parse_args(parser)

##Read in table 
pk<-read.delim(opt$input_filename, header = TRUE)
pk<-read.table("F:/Snail/longest_protO/Orthofinder/Results_May27/CAFE/Orthogroups.GeneCount.tsv", 
               header = TRUE)
row.names(pk)<-pk$Orthogroup
pk<-pk[,2:(ncol(pk)-1)]
nspecies=ncol(pk)
pk.count<-matrix(data = NA, ncol = 1, nrow = nrow(pk), dimnames = list(row.names(pk),"max"))
pk.count<-as.data.frame(pk.count)
pk.count$max = apply(pk, 1, max)
pk.count$min = apply(pk, 1, min)
pk.count$range = pk.count$max-pk.count$min
pk.count$sum = apply(pk, 1, sum)
pk.count$n0 = apply(pk,1,function(x) sum(x==0))
pk.count$n1 = apply(pk,1,function(x) sum(x<=1))
pk.count$osum = pk.count$sum-pk.count$max
pk.count$Orthogroup=row.names(pk.count)
pk$Desc<-"(null)"
pk$Orthogroup<-row.names(pk)
pk.new<-pk[,c("Desc", "Orthogroup")]
pk.new<-cbind(pk.new, pk[,1:(ncol(pk)-2)])

##At least 3 species got the gene for large difference family
pk.filter.list<-subset(pk.count, range >= 50 & n1 >= nspecies-3)
##large max with little genes in other species
pk.filter.list1<-subset(pk.count, range >= 50 & max/sum > 0.95)
pk.filter.list<-unique(rbind(pk.filter.list, pk.filter.list1))

pk.filter<-pk.new[-which(pk.new$Orthogroup %in% pk.filter.list$Orthogroup),]

##New table
write.table(pk.filter, 
            file = "cafe.input.filter.tsv",
            row.names = FALSE, quote = FALSE, sep = "\t")
