echo "Anaulaciulus_tonginus and Glomeris_maerens"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Anaulaciulus_tonginus__v__Glomeris_maerens.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Anaulaciulus_tonginus.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Glomeris_maerens.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Anaulaciulus_tonginus.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Glomeris_maerens.longest-gene.gtf --xspecies-name Anaulaciulus_tonginus --yspecies-name Glomeris_maerens --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Anaulaciulus_tonginus and Helicorthomorpha_holstii"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Anaulaciulus_tonginus__v__Helicorthomorpha_holstii.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Anaulaciulus_tonginus.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Helicorthomorpha_holstii.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Anaulaciulus_tonginus.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Helicorthomorpha_holstii.longest-gene.gtf --xspecies-name Anaulaciulus_tonginus --yspecies-name Helicorthomorpha_holstii --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Anaulaciulus_tonginus and Lithobius_niger"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Anaulaciulus_tonginus__v__Lithobius_niger.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Anaulaciulus_tonginus.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Lithobius_niger.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Anaulaciulus_tonginus.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Lithobius_niger.longest-gene.gtf --xspecies-name Anaulaciulus_tonginus --yspecies-name Lithobius_niger --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Anaulaciulus_tonginus and Niponia_nodulosa"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Anaulaciulus_tonginus__v__Niponia_nodulosa.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Anaulaciulus_tonginus.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Niponia_nodulosa.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Anaulaciulus_tonginus.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Niponia_nodulosa.longest-gene.gtf --xspecies-name Anaulaciulus_tonginus --yspecies-name Niponia_nodulosa --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Anaulaciulus_tonginus and Rhysida_immarginata"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Anaulaciulus_tonginus__v__Rhysida_immarginata.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Anaulaciulus_tonginus.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Rhysida_immarginata.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Anaulaciulus_tonginus.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Rhysida_immarginata.longest-gene.gtf --xspecies-name Anaulaciulus_tonginus --yspecies-name Rhysida_immarginata --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Anaulaciulus_tonginus and Strigamia_maritima"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Anaulaciulus_tonginus__v__Strigamia_maritima.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Anaulaciulus_tonginus.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Strigamia_maritima.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Anaulaciulus_tonginus.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Strigamia_maritima.longest-gene.gtf --xspecies-name Anaulaciulus_tonginus --yspecies-name Strigamia_maritima --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Anaulaciulus_tonginus and Thereuonema_tuberculata"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Anaulaciulus_tonginus__v__Thereuonema_tuberculata.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Anaulaciulus_tonginus.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Thereuonema_tuberculata.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Anaulaciulus_tonginus.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Thereuonema_tuberculata.longest-gene.gtf --xspecies-name Anaulaciulus_tonginus --yspecies-name Thereuonema_tuberculata --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Anaulaciulus_tonginus and Trigoniulus_corallinus"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Anaulaciulus_tonginus__v__Trigoniulus_corallinus.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Anaulaciulus_tonginus.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Trigoniulus_corallinus.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Anaulaciulus_tonginus.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Trigoniulus_corallinus.longest-gene.gtf --xspecies-name Anaulaciulus_tonginus --yspecies-name Trigoniulus_corallinus --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Glomeris_maerens and Anaulaciulus_tonginus"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Glomeris_maerens__v__Anaulaciulus_tonginus.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Glomeris_maerens.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Anaulaciulus_tonginus.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Glomeris_maerens.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Anaulaciulus_tonginus.longest-gene.gtf --xspecies-name Glomeris_maerens --yspecies-name Anaulaciulus_tonginus --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Glomeris_maerens and Helicorthomorpha_holstii"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Glomeris_maerens__v__Helicorthomorpha_holstii.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Glomeris_maerens.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Helicorthomorpha_holstii.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Glomeris_maerens.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Helicorthomorpha_holstii.longest-gene.gtf --xspecies-name Glomeris_maerens --yspecies-name Helicorthomorpha_holstii --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Glomeris_maerens and Lithobius_niger"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Glomeris_maerens__v__Lithobius_niger.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Glomeris_maerens.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Lithobius_niger.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Glomeris_maerens.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Lithobius_niger.longest-gene.gtf --xspecies-name Glomeris_maerens --yspecies-name Lithobius_niger --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Glomeris_maerens and Niponia_nodulosa"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Glomeris_maerens__v__Niponia_nodulosa.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Glomeris_maerens.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Niponia_nodulosa.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Glomeris_maerens.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Niponia_nodulosa.longest-gene.gtf --xspecies-name Glomeris_maerens --yspecies-name Niponia_nodulosa --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Glomeris_maerens and Rhysida_immarginata"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Glomeris_maerens__v__Rhysida_immarginata.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Glomeris_maerens.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Rhysida_immarginata.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Glomeris_maerens.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Rhysida_immarginata.longest-gene.gtf --xspecies-name Glomeris_maerens --yspecies-name Rhysida_immarginata --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Glomeris_maerens and Strigamia_maritima"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Glomeris_maerens__v__Strigamia_maritima.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Glomeris_maerens.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Strigamia_maritima.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Glomeris_maerens.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Strigamia_maritima.longest-gene.gtf --xspecies-name Glomeris_maerens --yspecies-name Strigamia_maritima --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Glomeris_maerens and Thereuonema_tuberculata"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Glomeris_maerens__v__Thereuonema_tuberculata.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Glomeris_maerens.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Thereuonema_tuberculata.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Glomeris_maerens.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Thereuonema_tuberculata.longest-gene.gtf --xspecies-name Glomeris_maerens --yspecies-name Thereuonema_tuberculata --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Glomeris_maerens and Trigoniulus_corallinus"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Glomeris_maerens__v__Trigoniulus_corallinus.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Glomeris_maerens.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Trigoniulus_corallinus.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Glomeris_maerens.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Trigoniulus_corallinus.longest-gene.gtf --xspecies-name Glomeris_maerens --yspecies-name Trigoniulus_corallinus --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Helicorthomorpha_holstii and Anaulaciulus_tonginus"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Helicorthomorpha_holstii__v__Anaulaciulus_tonginus.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Helicorthomorpha_holstii.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Anaulaciulus_tonginus.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Helicorthomorpha_holstii.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Anaulaciulus_tonginus.longest-gene.gtf --xspecies-name Helicorthomorpha_holstii --yspecies-name Anaulaciulus_tonginus --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Helicorthomorpha_holstii and Glomeris_maerens"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Helicorthomorpha_holstii__v__Glomeris_maerens.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Helicorthomorpha_holstii.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Glomeris_maerens.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Helicorthomorpha_holstii.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Glomeris_maerens.longest-gene.gtf --xspecies-name Helicorthomorpha_holstii --yspecies-name Glomeris_maerens --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Helicorthomorpha_holstii and Lithobius_niger"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Helicorthomorpha_holstii__v__Lithobius_niger.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Helicorthomorpha_holstii.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Lithobius_niger.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Helicorthomorpha_holstii.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Lithobius_niger.longest-gene.gtf --xspecies-name Helicorthomorpha_holstii --yspecies-name Lithobius_niger --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Helicorthomorpha_holstii and Niponia_nodulosa"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Helicorthomorpha_holstii__v__Niponia_nodulosa.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Helicorthomorpha_holstii.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Niponia_nodulosa.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Helicorthomorpha_holstii.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Niponia_nodulosa.longest-gene.gtf --xspecies-name Helicorthomorpha_holstii --yspecies-name Niponia_nodulosa --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Helicorthomorpha_holstii and Rhysida_immarginata"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Helicorthomorpha_holstii__v__Rhysida_immarginata.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Helicorthomorpha_holstii.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Rhysida_immarginata.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Helicorthomorpha_holstii.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Rhysida_immarginata.longest-gene.gtf --xspecies-name Helicorthomorpha_holstii --yspecies-name Rhysida_immarginata --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Helicorthomorpha_holstii and Strigamia_maritima"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Helicorthomorpha_holstii__v__Strigamia_maritima.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Helicorthomorpha_holstii.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Strigamia_maritima.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Helicorthomorpha_holstii.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Strigamia_maritima.longest-gene.gtf --xspecies-name Helicorthomorpha_holstii --yspecies-name Strigamia_maritima --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Helicorthomorpha_holstii and Thereuonema_tuberculata"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Helicorthomorpha_holstii__v__Thereuonema_tuberculata.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Helicorthomorpha_holstii.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Thereuonema_tuberculata.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Helicorthomorpha_holstii.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Thereuonema_tuberculata.longest-gene.gtf --xspecies-name Helicorthomorpha_holstii --yspecies-name Thereuonema_tuberculata --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Helicorthomorpha_holstii and Trigoniulus_corallinus"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Helicorthomorpha_holstii__v__Trigoniulus_corallinus.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Helicorthomorpha_holstii.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Trigoniulus_corallinus.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Helicorthomorpha_holstii.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Trigoniulus_corallinus.longest-gene.gtf --xspecies-name Helicorthomorpha_holstii --yspecies-name Trigoniulus_corallinus --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Lithobius_niger and Anaulaciulus_tonginus"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Lithobius_niger__v__Anaulaciulus_tonginus.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Lithobius_niger.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Anaulaciulus_tonginus.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Lithobius_niger.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Anaulaciulus_tonginus.longest-gene.gtf --xspecies-name Lithobius_niger --yspecies-name Anaulaciulus_tonginus --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Lithobius_niger and Glomeris_maerens"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Lithobius_niger__v__Glomeris_maerens.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Lithobius_niger.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Glomeris_maerens.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Lithobius_niger.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Glomeris_maerens.longest-gene.gtf --xspecies-name Lithobius_niger --yspecies-name Glomeris_maerens --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Lithobius_niger and Helicorthomorpha_holstii"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Lithobius_niger__v__Helicorthomorpha_holstii.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Lithobius_niger.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Helicorthomorpha_holstii.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Lithobius_niger.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Helicorthomorpha_holstii.longest-gene.gtf --xspecies-name Lithobius_niger --yspecies-name Helicorthomorpha_holstii --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Lithobius_niger and Niponia_nodulosa"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Lithobius_niger__v__Niponia_nodulosa.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Lithobius_niger.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Niponia_nodulosa.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Lithobius_niger.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Niponia_nodulosa.longest-gene.gtf --xspecies-name Lithobius_niger --yspecies-name Niponia_nodulosa --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Lithobius_niger and Rhysida_immarginata"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Lithobius_niger__v__Rhysida_immarginata.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Lithobius_niger.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Rhysida_immarginata.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Lithobius_niger.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Rhysida_immarginata.longest-gene.gtf --xspecies-name Lithobius_niger --yspecies-name Rhysida_immarginata --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Lithobius_niger and Strigamia_maritima"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Lithobius_niger__v__Strigamia_maritima.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Lithobius_niger.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Strigamia_maritima.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Lithobius_niger.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Strigamia_maritima.longest-gene.gtf --xspecies-name Lithobius_niger --yspecies-name Strigamia_maritima --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Lithobius_niger and Thereuonema_tuberculata"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Lithobius_niger__v__Thereuonema_tuberculata.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Lithobius_niger.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Thereuonema_tuberculata.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Lithobius_niger.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Thereuonema_tuberculata.longest-gene.gtf --xspecies-name Lithobius_niger --yspecies-name Thereuonema_tuberculata --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Lithobius_niger and Trigoniulus_corallinus"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Lithobius_niger__v__Trigoniulus_corallinus.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Lithobius_niger.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Trigoniulus_corallinus.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Lithobius_niger.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Trigoniulus_corallinus.longest-gene.gtf --xspecies-name Lithobius_niger --yspecies-name Trigoniulus_corallinus --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Niponia_nodulosa and Anaulaciulus_tonginus"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Niponia_nodulosa__v__Anaulaciulus_tonginus.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Niponia_nodulosa.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Anaulaciulus_tonginus.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Niponia_nodulosa.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Anaulaciulus_tonginus.longest-gene.gtf --xspecies-name Niponia_nodulosa --yspecies-name Anaulaciulus_tonginus --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Niponia_nodulosa and Glomeris_maerens"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Niponia_nodulosa__v__Glomeris_maerens.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Niponia_nodulosa.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Glomeris_maerens.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Niponia_nodulosa.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Glomeris_maerens.longest-gene.gtf --xspecies-name Niponia_nodulosa --yspecies-name Glomeris_maerens --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Niponia_nodulosa and Helicorthomorpha_holstii"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Niponia_nodulosa__v__Helicorthomorpha_holstii.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Niponia_nodulosa.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Helicorthomorpha_holstii.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Niponia_nodulosa.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Helicorthomorpha_holstii.longest-gene.gtf --xspecies-name Niponia_nodulosa --yspecies-name Helicorthomorpha_holstii --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Niponia_nodulosa and Lithobius_niger"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Niponia_nodulosa__v__Lithobius_niger.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Niponia_nodulosa.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Lithobius_niger.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Niponia_nodulosa.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Lithobius_niger.longest-gene.gtf --xspecies-name Niponia_nodulosa --yspecies-name Lithobius_niger --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Niponia_nodulosa and Rhysida_immarginata"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Niponia_nodulosa__v__Rhysida_immarginata.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Niponia_nodulosa.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Rhysida_immarginata.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Niponia_nodulosa.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Rhysida_immarginata.longest-gene.gtf --xspecies-name Niponia_nodulosa --yspecies-name Rhysida_immarginata --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Niponia_nodulosa and Strigamia_maritima"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Niponia_nodulosa__v__Strigamia_maritima.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Niponia_nodulosa.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Strigamia_maritima.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Niponia_nodulosa.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Strigamia_maritima.longest-gene.gtf --xspecies-name Niponia_nodulosa --yspecies-name Strigamia_maritima --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Niponia_nodulosa and Thereuonema_tuberculata"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Niponia_nodulosa__v__Thereuonema_tuberculata.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Niponia_nodulosa.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Thereuonema_tuberculata.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Niponia_nodulosa.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Thereuonema_tuberculata.longest-gene.gtf --xspecies-name Niponia_nodulosa --yspecies-name Thereuonema_tuberculata --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Niponia_nodulosa and Trigoniulus_corallinus"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Niponia_nodulosa__v__Trigoniulus_corallinus.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Niponia_nodulosa.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Trigoniulus_corallinus.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Niponia_nodulosa.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Trigoniulus_corallinus.longest-gene.gtf --xspecies-name Niponia_nodulosa --yspecies-name Trigoniulus_corallinus --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Rhysida_immarginata and Anaulaciulus_tonginus"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Rhysida_immarginata__v__Anaulaciulus_tonginus.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Rhysida_immarginata.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Anaulaciulus_tonginus.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Rhysida_immarginata.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Anaulaciulus_tonginus.longest-gene.gtf --xspecies-name Rhysida_immarginata --yspecies-name Anaulaciulus_tonginus --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Rhysida_immarginata and Glomeris_maerens"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Rhysida_immarginata__v__Glomeris_maerens.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Rhysida_immarginata.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Glomeris_maerens.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Rhysida_immarginata.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Glomeris_maerens.longest-gene.gtf --xspecies-name Rhysida_immarginata --yspecies-name Glomeris_maerens --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Rhysida_immarginata and Helicorthomorpha_holstii"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Rhysida_immarginata__v__Helicorthomorpha_holstii.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Rhysida_immarginata.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Helicorthomorpha_holstii.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Rhysida_immarginata.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Helicorthomorpha_holstii.longest-gene.gtf --xspecies-name Rhysida_immarginata --yspecies-name Helicorthomorpha_holstii --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Rhysida_immarginata and Lithobius_niger"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Rhysida_immarginata__v__Lithobius_niger.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Rhysida_immarginata.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Lithobius_niger.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Rhysida_immarginata.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Lithobius_niger.longest-gene.gtf --xspecies-name Rhysida_immarginata --yspecies-name Lithobius_niger --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Rhysida_immarginata and Niponia_nodulosa"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Rhysida_immarginata__v__Niponia_nodulosa.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Rhysida_immarginata.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Niponia_nodulosa.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Rhysida_immarginata.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Niponia_nodulosa.longest-gene.gtf --xspecies-name Rhysida_immarginata --yspecies-name Niponia_nodulosa --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Rhysida_immarginata and Strigamia_maritima"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Rhysida_immarginata__v__Strigamia_maritima.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Rhysida_immarginata.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Strigamia_maritima.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Rhysida_immarginata.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Strigamia_maritima.longest-gene.gtf --xspecies-name Rhysida_immarginata --yspecies-name Strigamia_maritima --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Rhysida_immarginata and Thereuonema_tuberculata"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Rhysida_immarginata__v__Thereuonema_tuberculata.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Rhysida_immarginata.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Thereuonema_tuberculata.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Rhysida_immarginata.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Thereuonema_tuberculata.longest-gene.gtf --xspecies-name Rhysida_immarginata --yspecies-name Thereuonema_tuberculata --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Rhysida_immarginata and Trigoniulus_corallinus"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Rhysida_immarginata__v__Trigoniulus_corallinus.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Rhysida_immarginata.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Trigoniulus_corallinus.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Rhysida_immarginata.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Trigoniulus_corallinus.longest-gene.gtf --xspecies-name Rhysida_immarginata --yspecies-name Trigoniulus_corallinus --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Strigamia_maritima and Anaulaciulus_tonginus"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Strigamia_maritima__v__Anaulaciulus_tonginus.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Strigamia_maritima.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Anaulaciulus_tonginus.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Strigamia_maritima.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Anaulaciulus_tonginus.longest-gene.gtf --xspecies-name Strigamia_maritima --yspecies-name Anaulaciulus_tonginus --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Strigamia_maritima and Glomeris_maerens"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Strigamia_maritima__v__Glomeris_maerens.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Strigamia_maritima.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Glomeris_maerens.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Strigamia_maritima.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Glomeris_maerens.longest-gene.gtf --xspecies-name Strigamia_maritima --yspecies-name Glomeris_maerens --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Strigamia_maritima and Helicorthomorpha_holstii"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Strigamia_maritima__v__Helicorthomorpha_holstii.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Strigamia_maritima.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Helicorthomorpha_holstii.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Strigamia_maritima.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Helicorthomorpha_holstii.longest-gene.gtf --xspecies-name Strigamia_maritima --yspecies-name Helicorthomorpha_holstii --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Strigamia_maritima and Lithobius_niger"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Strigamia_maritima__v__Lithobius_niger.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Strigamia_maritima.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Lithobius_niger.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Strigamia_maritima.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Lithobius_niger.longest-gene.gtf --xspecies-name Strigamia_maritima --yspecies-name Lithobius_niger --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Strigamia_maritima and Niponia_nodulosa"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Strigamia_maritima__v__Niponia_nodulosa.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Strigamia_maritima.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Niponia_nodulosa.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Strigamia_maritima.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Niponia_nodulosa.longest-gene.gtf --xspecies-name Strigamia_maritima --yspecies-name Niponia_nodulosa --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Strigamia_maritima and Rhysida_immarginata"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Strigamia_maritima__v__Rhysida_immarginata.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Strigamia_maritima.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Rhysida_immarginata.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Strigamia_maritima.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Rhysida_immarginata.longest-gene.gtf --xspecies-name Strigamia_maritima --yspecies-name Rhysida_immarginata --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Strigamia_maritima and Thereuonema_tuberculata"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Strigamia_maritima__v__Thereuonema_tuberculata.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Strigamia_maritima.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Thereuonema_tuberculata.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Strigamia_maritima.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Thereuonema_tuberculata.longest-gene.gtf --xspecies-name Strigamia_maritima --yspecies-name Thereuonema_tuberculata --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Strigamia_maritima and Trigoniulus_corallinus"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Strigamia_maritima__v__Trigoniulus_corallinus.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Strigamia_maritima.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Trigoniulus_corallinus.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Strigamia_maritima.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Trigoniulus_corallinus.longest-gene.gtf --xspecies-name Strigamia_maritima --yspecies-name Trigoniulus_corallinus --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Thereuonema_tuberculata and Anaulaciulus_tonginus"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Thereuonema_tuberculata__v__Anaulaciulus_tonginus.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Thereuonema_tuberculata.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Anaulaciulus_tonginus.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Thereuonema_tuberculata.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Anaulaciulus_tonginus.longest-gene.gtf --xspecies-name Thereuonema_tuberculata --yspecies-name Anaulaciulus_tonginus --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Thereuonema_tuberculata and Glomeris_maerens"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Thereuonema_tuberculata__v__Glomeris_maerens.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Thereuonema_tuberculata.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Glomeris_maerens.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Thereuonema_tuberculata.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Glomeris_maerens.longest-gene.gtf --xspecies-name Thereuonema_tuberculata --yspecies-name Glomeris_maerens --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Thereuonema_tuberculata and Helicorthomorpha_holstii"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Thereuonema_tuberculata__v__Helicorthomorpha_holstii.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Thereuonema_tuberculata.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Helicorthomorpha_holstii.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Thereuonema_tuberculata.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Helicorthomorpha_holstii.longest-gene.gtf --xspecies-name Thereuonema_tuberculata --yspecies-name Helicorthomorpha_holstii --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Thereuonema_tuberculata and Lithobius_niger"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Thereuonema_tuberculata__v__Lithobius_niger.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Thereuonema_tuberculata.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Lithobius_niger.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Thereuonema_tuberculata.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Lithobius_niger.longest-gene.gtf --xspecies-name Thereuonema_tuberculata --yspecies-name Lithobius_niger --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Thereuonema_tuberculata and Niponia_nodulosa"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Thereuonema_tuberculata__v__Niponia_nodulosa.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Thereuonema_tuberculata.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Niponia_nodulosa.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Thereuonema_tuberculata.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Niponia_nodulosa.longest-gene.gtf --xspecies-name Thereuonema_tuberculata --yspecies-name Niponia_nodulosa --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Thereuonema_tuberculata and Rhysida_immarginata"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Thereuonema_tuberculata__v__Rhysida_immarginata.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Thereuonema_tuberculata.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Rhysida_immarginata.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Thereuonema_tuberculata.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Rhysida_immarginata.longest-gene.gtf --xspecies-name Thereuonema_tuberculata --yspecies-name Rhysida_immarginata --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Thereuonema_tuberculata and Strigamia_maritima"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Thereuonema_tuberculata__v__Strigamia_maritima.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Thereuonema_tuberculata.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Strigamia_maritima.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Thereuonema_tuberculata.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Strigamia_maritima.longest-gene.gtf --xspecies-name Thereuonema_tuberculata --yspecies-name Strigamia_maritima --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Thereuonema_tuberculata and Trigoniulus_corallinus"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Thereuonema_tuberculata__v__Trigoniulus_corallinus.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Thereuonema_tuberculata.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Trigoniulus_corallinus.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Thereuonema_tuberculata.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Trigoniulus_corallinus.longest-gene.gtf --xspecies-name Thereuonema_tuberculata --yspecies-name Trigoniulus_corallinus --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Trigoniulus_corallinus and Anaulaciulus_tonginus"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Trigoniulus_corallinus__v__Anaulaciulus_tonginus.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Trigoniulus_corallinus.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Anaulaciulus_tonginus.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Trigoniulus_corallinus.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Anaulaciulus_tonginus.longest-gene.gtf --xspecies-name Trigoniulus_corallinus --yspecies-name Anaulaciulus_tonginus --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Trigoniulus_corallinus and Glomeris_maerens"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Trigoniulus_corallinus__v__Glomeris_maerens.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Trigoniulus_corallinus.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Glomeris_maerens.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Trigoniulus_corallinus.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Glomeris_maerens.longest-gene.gtf --xspecies-name Trigoniulus_corallinus --yspecies-name Glomeris_maerens --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Trigoniulus_corallinus and Helicorthomorpha_holstii"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Trigoniulus_corallinus__v__Helicorthomorpha_holstii.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Trigoniulus_corallinus.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Helicorthomorpha_holstii.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Trigoniulus_corallinus.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Helicorthomorpha_holstii.longest-gene.gtf --xspecies-name Trigoniulus_corallinus --yspecies-name Helicorthomorpha_holstii --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Trigoniulus_corallinus and Lithobius_niger"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Trigoniulus_corallinus__v__Lithobius_niger.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Trigoniulus_corallinus.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Lithobius_niger.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Trigoniulus_corallinus.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Lithobius_niger.longest-gene.gtf --xspecies-name Trigoniulus_corallinus --yspecies-name Lithobius_niger --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Trigoniulus_corallinus and Niponia_nodulosa"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Trigoniulus_corallinus__v__Niponia_nodulosa.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Trigoniulus_corallinus.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Niponia_nodulosa.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Trigoniulus_corallinus.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Niponia_nodulosa.longest-gene.gtf --xspecies-name Trigoniulus_corallinus --yspecies-name Niponia_nodulosa --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Trigoniulus_corallinus and Rhysida_immarginata"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Trigoniulus_corallinus__v__Rhysida_immarginata.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Trigoniulus_corallinus.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Rhysida_immarginata.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Trigoniulus_corallinus.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Rhysida_immarginata.longest-gene.gtf --xspecies-name Trigoniulus_corallinus --yspecies-name Rhysida_immarginata --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Trigoniulus_corallinus and Strigamia_maritima"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Trigoniulus_corallinus__v__Strigamia_maritima.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Trigoniulus_corallinus.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Strigamia_maritima.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Trigoniulus_corallinus.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Strigamia_maritima.longest-gene.gtf --xspecies-name Trigoniulus_corallinus --yspecies-name Strigamia_maritima --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
echo "Trigoniulus_corallinus and Thereuonema_tuberculata"
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Trigoniulus_corallinus__v__Thereuonema_tuberculata.tsv.txt --xspecies-fai /jelly_data/yichun/myriapod/fai/Trigoniulus_corallinus.fa.fai --yspecies-fai /jelly_data/yichun/myriapod/fai/Thereuonema_tuberculata.fa.fai --xspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Trigoniulus_corallinus.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/myriapod/gtf/formatted.Thereuonema_tuberculata.longest-gene.gtf --xspecies-name Trigoniulus_corallinus --yspecies-name Thereuonema_tuberculata --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
